# Generated by Django 5.0.7 on 2024-08-25 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=64)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('data_emissao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('senha', models.CharField(max_length=64)),
                ('id_certificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlogic.certificacao')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=1500)),
                ('data_publicacao', models.DateField()),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlogic.instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlogic.disciplina')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlogic.material')),
            ],
        ),
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título do Resumo', max_length=100)),
                ('conteudo', models.CharField(max_length=8000)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlogic.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaResumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlogic.disciplina')),
                ('resumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlogic.resumo')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaInstrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlogic.disciplina')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlogic.instrutor')),
            ],
            options={
                'unique_together': {('instrutor', 'disciplina')},
            },
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('autor', 'titulo'), name='unique_autor_titulo'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinamaterial',
            unique_together={('disciplina', 'material')},
        ),
        migrations.AddConstraint(
            model_name='disciplinaresumo',
            constraint=models.UniqueConstraint(fields=('disciplina', 'resumo'), name='unique_disciplina_resumo'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaresumo',
            unique_together={('disciplina', 'resumo')},
        ),
    ]
